ALTER TABLE sys_login_log ADD COLUMN IF NOT EXISTS nickname VARCHAR(128);
ALTER TABLE sys_login_log ADD COLUMN IF NOT EXISTS email VARCHAR(128);
ALTER TABLE sys_login_log ADD COLUMN IF NOT EXISTS address VARCHAR(128);
