CREATE TABLE IF NOT EXISTS biz_knowledge (
 id BIGSERIAL PRIMARY KEY, title VARCHAR(160) NOT NULL, category VARCHAR(64), summary VARCHAR(500), content TEXT NOT NULL, view_count BIGINT NOT NULL DEFAULT 0, like_count BIGINT NOT NULL DEFAULT 0, favorite_count BIGINT NOT NULL DEFAULT 0,
 status SMALLINT NOT NULL DEFAULT 0, create_time TIMESTAMP NOT NULL DEFAULT NOW(), update_time TIMESTAMP NOT NULL DEFAULT NOW(), create_by BIGINT, is_deleted SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_biz_knowledge_status ON biz_knowledge(status);
ALTER TABLE biz_knowledge ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE biz_knowledge ADD COLUMN IF NOT EXISTS like_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE biz_knowledge ADD COLUMN IF NOT EXISTS favorite_count BIGINT NOT NULL DEFAULT 0;
