CREATE TABLE IF NOT EXISTS biz_feedback (
    id BIGSERIAL PRIMARY KEY, user_id BIGINT, name VARCHAR(64) NOT NULL, company VARCHAR(128), contact VARCHAR(128) NOT NULL,
    type VARCHAR(32), description TEXT NOT NULL, status SMALLINT NOT NULL DEFAULT 0,
    create_time TIMESTAMP NOT NULL DEFAULT NOW(), update_time TIMESTAMP NOT NULL DEFAULT NOW(), is_deleted SMALLINT NOT NULL DEFAULT 0
);
